version: '3'
services:
  portal_zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: portal_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'

  portal_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: portal_kafka
    depends_on:
      - portal_zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: portal_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.tcp.in.ngrok.io:14810
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        # The big fixes for single-broker:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
